### ISSUE TITLE
Triggered from Google assistant Always goes to heating mode 

### ISSUE THREAD

**Issue by mimik0** [zacs/ha-dualmodegeneric#56]
Hi, first good job for this plugin it works very well, i only have one problem, when it's turned off and i want to turn it back on, it always goes to heating mode and not to the previous mode.

Thanks for what you can do 😉

**Comment by david-kalbermatten** [comment]
This is due to how the `ClimateEntity` in Home Assistant has evolved over the years. I used to only allow to have an operating mode selected (off, cool, heat, ...). With the somewhat recent changes the devs have introduced the ability to call `climate.turn_on` and `climate.turn_off` and also implemented a default logic for those actions which is being used when an Integration (like this one) hasn't implemented the changes.

This is also why you probably saw loads of deprecation warnings in the logs every time the climate was manually turned on/off

#66 should fix this among other things.

**Comment by david-kalbermatten** [comment]
I just merged #66. Please check if your Issue has been resolved after the update

**Comment by mimik0** [comment]
> I just merged #66. Please check if your Issue has been resolved after the update

Yes all good !
